import { expect, test } from 'bun:test'
import { formatRow, formatTimeline, projectName, relTime, tierGlyph, userPromptText } from '../src/render'
import type { Row } from '../src/core/query'

const NOW = 1_800_000_000_000
const MIN = 60_000
const HOUR = 3_600_000
const DAY = 86_400_000

test('relTime formats compactly', () => {
  expect(relTime(NOW - 30_000, NOW)).toBe('now')
  expect(relTime(NOW - 5 * MIN, NOW)).toBe('5m')
  expect(relTime(NOW - 3 * HOUR, NOW)).toBe('3h')
  expect(relTime(NOW - 2 * DAY, NOW)).toBe('2d')
  expect(relTime(NOW - 40 * DAY, NOW)).toBe('5w')
  expect(relTime(NOW - 400 * DAY, NOW)).toBe('1y')
})

test('relTime does not go negative for a clock skew in the future', () => {
  expect(relTime(NOW + 10 * DAY, NOW)).toBe('now')
})

test('row rendering is compact and includes tier and collapsed-count facets', () => {
  const row = {
    uid: 'claude:id', client: 'claude', nativeId: 'id', cwd: '/root/a-very-long-project-name',
    gitBranch: null, title: null, startedAt: NOW, endedAt: NOW - 5 * MIN, turns: 1,
    parentNativeId: null, tier: 'resume', origin: 'manifest',
    missing: false, score: 1, collapsed: 2,
  } satisfies Row
  expect(projectName(null)).toBe('-')
  expect(projectName('/')).toBe('/')
  expect(tierGlyph('resume')).toBe('*')
  expect(tierGlyph('search')).toBe('o')
  expect(formatRow(row, NOW)).toContain('*  claude')
  expect(formatRow(row, NOW)).toContain('(no title)  +2')
  expect(formatRow(row, NOW)).toContain('a-very-long-proj')
})

test('harness wrappers are unwrapped into what was actually asked', () => {
  // A slash command carries its intent in the arguments, so both are kept.
  expect(userPromptText(
    '<command-message>blog-ideas</command-message>\n'
    + '<command-name>/blog-ideas</command-name>\n'
    + '<command-args>fresh news, but i want it to be a tutorial</command-args>',
  )).toBe('/blog-ideas fresh news, but i want it to be a tutorial')

  // A command with no arguments still says which command it was.
  expect(userPromptText(
    '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n'
    + '            <command-args></command-args>',
  )).toBe('/exit')

  // These three are written by the harness, not typed, so nothing survives.
  expect(userPromptText(
    '<local-command-caveat>Caveat: The messages below were generated by the user while'
    + ' running local commands.</local-command-caveat>',
  )).toBe('')
  expect(userPromptText('<local-command-stdout>Bye!</local-command-stdout>')).toBe('')
  expect(userPromptText(
    'Base directory for this skill: /root/x/.claude/skills/blog-ideas\n\n# Blog Ideas\n\nScan discourse.',
  )).toBe('')

  // A caveat wrapped around a real prompt leaves the prompt behind.
  expect(userPromptText(
    '<local-command-caveat>Caveat: ignore this.</local-command-caveat>\nfix the retry budget',
  )).toBe('fix the retry budget')

  // Ordinary prompts are untouched beyond trimming.
  expect(userPromptText('  fix the retry budget  ')).toBe('fix the retry budget')
  expect(userPromptText('')).toBe('')
  expect(userPromptText('a < b and 3 > 2')).toBe('a < b and 3 > 2')
})

test('a title carrying an escape sequence or a bidi override is neutralised', () => {
  const row = {
    uid: 'claude:id', client: 'claude', nativeId: 'id', cwd: '/root/nekyia',
    gitBranch: null, title: '\u001b[2J\u001b[Hwiped\u202edesrever', startedAt: NOW,
    endedAt: NOW - 5 * MIN, turns: 1, parentNativeId: null, tier: 'resume',
    origin: 'manifest', missing: false,
    score: 1, collapsed: 0,
  } satisfies Row
  const line = formatRow(row, NOW)
  // The introducer becomes a space, so the screen-clear reads as text, not as a command.
  expect(line).not.toContain('\u001b')
  expect(line).toContain('[2J [Hwiped')
  // The override is dropped outright: a replacement space would still shift the line.
  expect(line).not.toContain('\u202e')
  expect(line).toContain('wipeddesrever')
})

test('a wide project name still occupies exactly sixteen terminal columns', () => {
  const row = {
    uid: 'claude:id', client: 'claude', nativeId: 'id', cwd: '/root/日本語プロジェクト名前',
    gitBranch: null, title: 'x', startedAt: NOW, endedAt: NOW - 5 * MIN, turns: 1,
    parentNativeId: null, tier: 'resume', origin: 'manifest',
    missing: false, score: 1, collapsed: 0,
  } satisfies Row
  const line = formatRow(row, NOW)
  // The glyph, client and age columns with their separators cost twenty columns.
  const project = line.slice(20, 20 + '日本語プロジェク'.length)
  expect(Bun.stringWidth(project)).toBe(16)
  expect(line.slice(20 + '日本語プロジェク'.length)).toBe('  x')
  // Eight double-width graphemes fill the column; the ninth is dropped whole.
  expect(project).toBe('日本語プロジェク')

  // A short wide name is padded by display width: padEnd would have counted the
  // two code units of 日本 as two columns and left the title four columns adrift.
  const short = formatRow({ ...row, cwd: '/root/日本' }, NOW)
  expect(short.slice(20)).toBe(`日本${' '.repeat(12)}  x`)
})

test('an unbounded title is cut to the title column', () => {
  const row = {
    uid: 'claude:id', client: 'claude', nativeId: 'id', cwd: '/root/nekyia',
    gitBranch: null, title: 'a'.repeat(5_000), startedAt: NOW, endedAt: NOW - 5 * MIN,
    turns: 1, parentNativeId: null, tier: 'resume', origin: 'manifest',
    missing: false, score: 3, collapsed: 0,
  } satisfies Row
  expect(formatRow(row, NOW)).toContain('a'.repeat(120))
  expect(formatRow(row, NOW)).not.toContain('a'.repeat(121))
})

test('a timeline groups events under their session', () => {
  const lines=formatTimeline([{
    ref: { uid:'claude:a', client:'claude', nativeId:'a', cwd:'/root/proj', gitBranch:'main',
      title:'fix the sse race', startedAt:1000, endedAt:2000, turns:4, parentNativeId:null,
      tier:'resume', origin:'manifest', missing:false },
    detail:'ordered', eventsTruncated:false,
    entries:[
      { ordinal:0, turn:3, kind:'edit', path:'src/sse.ts', resolved:'/root/proj/src/sse.ts' },
      { ordinal:1, turn:9, kind:'delete', path:'scratch.ts', resolved:'/root/proj/scratch.ts' },
    ],
  }], { dir:'/root/proj', git:{ consulted:true, tracked:new Set(['/root/proj/src/sse.ts']) }, now:2000 })
  expect(lines.join('\n')).toContain('3  edit    src/sse.ts')
  expect(lines.join('\n')).toContain('9  delete  scratch.ts')
  expect(lines.join('\n')).toContain('untracked')
})
test('a paths-only session says so instead of showing an order', () => {
  const lines=formatTimeline([{
    ref: { uid:'copilot:b', client:'copilot', nativeId:'b', cwd:'/root/proj', gitBranch:null,
      title:null, startedAt:1000, endedAt:2000, turns:0, parentNativeId:null,
      tier:'search', origin:'manifest', missing:false },
    detail:'paths', eventsTruncated:false,
    entries:[{ ordinal:null, turn:null, kind:'unknown', path:'src/db.ts', resolved:'/root/proj/src/db.ts' }],
  }], { dir:'/root/proj', git:{ consulted:false, tracked:new Set() }, now:2000 })
  expect(lines.join('\n')).toContain('this client records file names only')
  expect(lines.join('\n')).not.toContain('untracked')
})
test('sessions indexed before file events are counted in the header', () => {
  const lines=formatTimeline([{
    ref: { uid:'claude:c', client:'claude', nativeId:'c', cwd:'/root/proj', gitBranch:null,
      title:null, startedAt:1000, endedAt:2000, turns:0, parentNativeId:null,
      tier:'resume', origin:'manifest', missing:false },
    detail:'unknown', eventsTruncated:false,
    entries:[{ ordinal:null, turn:null, kind:'unknown', path:'x.ts', resolved:'/root/proj/x.ts' }],
  }], { dir:'/root/proj', git:{ consulted:false, tracked:new Set() }, now:2000 })
  expect(lines.join('\n')).toContain('run "nekyia index"')
})
