import { expect, test } from 'bun:test'
import { formatRow, projectName, relTime, tierGlyph, userPromptText } from '../src/render'
import type { Row } from '../src/core/query'

const NOW = 1_800_000_000_000
const MIN = 60_000
const HOUR = 3_600_000
const DAY = 86_400_000

test('relTime formats compactly', () => {
  expect(relTime(NOW - 30_000, NOW)).toBe('now')
  expect(relTime(NOW - 5 * MIN, NOW)).toBe('5m')
  expect(relTime(NOW - 3 * HOUR, NOW)).toBe('3h')
  expect(relTime(NOW - 2 * DAY, NOW)).toBe('2d')
  expect(relTime(NOW - 40 * DAY, NOW)).toBe('5w')
  expect(relTime(NOW - 400 * DAY, NOW)).toBe('1y')
})

test('relTime does not go negative for a clock skew in the future', () => {
  expect(relTime(NOW + 10 * DAY, NOW)).toBe('now')
})

test('row rendering is compact and includes tier and collapsed-count facets', () => {
  const row = {
    uid: 'claude:id', client: 'claude', nativeId: 'id', cwd: '/root/a-very-long-project-name',
    gitBranch: null, title: null, startedAt: NOW, endedAt: NOW - 5 * MIN, turns: 1,
    parentNativeId: null, tier: 'resume', origin: 'manifest', sourcePaths: [],
    fingerprint: 'f', missing: false, score: 1, collapsed: 2,
  } satisfies Row
  expect(projectName(null)).toBe('-')
  expect(projectName('/')).toBe('/')
  expect(tierGlyph('resume')).toBe('*')
  expect(tierGlyph('search')).toBe('o')
  expect(formatRow(row, NOW)).toContain('*  claude')
  expect(formatRow(row, NOW)).toContain('(no title)  +2')
  expect(formatRow(row, NOW)).toContain('a-very-long-proj')
})

test('harness wrappers are unwrapped into what was actually asked', () => {
  // A slash command carries its intent in the arguments, so both are kept.
  expect(userPromptText(
    '<command-message>blog-ideas</command-message>\n'
    + '<command-name>/blog-ideas</command-name>\n'
    + '<command-args>fresh news, but i want it to be a tutorial</command-args>',
  )).toBe('/blog-ideas fresh news, but i want it to be a tutorial')

  // A command with no arguments still says which command it was.
  expect(userPromptText(
    '<command-name>/exit</command-name>\n            <command-message>exit</command-message>\n'
    + '            <command-args></command-args>',
  )).toBe('/exit')

  // These three are written by the harness, not typed, so nothing survives.
  expect(userPromptText(
    '<local-command-caveat>Caveat: The messages below were generated by the user while'
    + ' running local commands.</local-command-caveat>',
  )).toBe('')
  expect(userPromptText('<local-command-stdout>Bye!</local-command-stdout>')).toBe('')
  expect(userPromptText(
    'Base directory for this skill: /root/x/.claude/skills/blog-ideas\n\n# Blog Ideas\n\nScan discourse.',
  )).toBe('')

  // A caveat wrapped around a real prompt leaves the prompt behind.
  expect(userPromptText(
    '<local-command-caveat>Caveat: ignore this.</local-command-caveat>\nfix the retry budget',
  )).toBe('fix the retry budget')

  // Ordinary prompts are untouched beyond trimming.
  expect(userPromptText('  fix the retry budget  ')).toBe('fix the retry budget')
  expect(userPromptText('')).toBe('')
  expect(userPromptText('a < b and 3 > 2')).toBe('a < b and 3 > 2')
})
